### ISSUE TITLE
Add suitable favicon to minimal mistakes jekyll theme

### ISSUE THREAD

**Issue by pavanjoshi914** [pavanjoshi914/Blog#4]
solving ```Favicon.ico not found```  in minimal mistake jekyll theme

```error```
![2021-06-14_12-48](https://user-images.githubusercontent.com/55848322/121853779-f941b000-cd0e-11eb-86eb-b126df02daa7.png)

```unexpected output```
![2021-06-14_12-45](https://user-images.githubusercontent.com/55848322/121853461-95b78280-cd0e-11eb-84c8-3a6406d53a1b.png)

possible solution:

https://github.com/mmistakes/minimal-mistakes/issues/949

https://ptc-it.de/add-favicon-to-mm-jekyll-site/

**Comment by thebhavana** [comment]
- The appropriate size of favicon image is 16 by 16 px , at max 32 by 32 px.
-  You are using 48 pixels, maybe an error.

**Comment by pavanjoshi914** [comment]
If possible please generate pr for the same

**Comment by pavanjoshi914** [comment]
fixed in 2be7d48e1edaf03bb710b96195b43cbde5b0e40d b78952b1ad5f1f27f01c19db47ceda67d2793914 8071a27f674738f2b91ca24caa5091ce95c656d6
